### ISSUE TITLE
provide enhanced `oc` commands

### ISSUE THREAD

**Issue by starpit** [kui-shell/AnimalApp#200]
#199 covers adding a basic level of support for openshift, for those commands where `oc` delegates over to kubectl.

we can enhance this further, perhaps. we should investigate how the more openshift-oriented commands could be enhanced with graphics

origin: IBM/kui#3441
requested by: @honghuac

**Comment by honghuac** [comment]
@starpit Recommended approach, track the changes to **oc** utility by following the [repo](https://github.com/openshift/oc).
