### ISSUE TITLE
[Question] Is it possible to run actions on kubernetes resources through KUI?

### ISSUE THREAD

**Issue by akavel** [kui-shell/AnimalApp#233]
When I found a pod I'm interested in through the KUI & "sidecar", is there some easy way how I can e.g. delete it? or do I still have to copy full name of the resource, as in normal terminal, and type a normal `kubectl delete -n $NAMESPACE $RESOURCE` command by hand, pasting the name of the resource & namespace? I don't seem to see any "delete" button or similar in the sidecar or in the main KUI window; I tried right-clicking too on various parts of the windows, but doesn't seem to do anything.

**Comment by starpit** [comment]
hi, thanks for the question, and sorry for the delay in our response!

do you see the "Delete this Resource" button in the sidecar? if not, could you take a screenshot of what you do see? thanks!

![image](https://user-images.githubusercontent.com/4741620/73084911-cf7ab580-3e9b-11ea-9c5a-c52402b3726c.png)
