### ISSUE TITLE
`oc help` command can be rendered as menu

### ISSUE THREAD

**Issue by myan9** [kui-shell/AnimalApp#434]
We already have `oc {get, run, delete, describe, apply, create} -h` rendered as usage menu. We can also render `oc help` as a menu.

For example: `oc get -h`
![image](https://user-images.githubusercontent.com/21212160/77205549-7a3dd780-6acb-11ea-8e56-7222d580a655.png)

**Comment by starpit** [comment]
nice catch!

**Comment by starpit** [comment]
same with `helm`
