### ISSUE TITLE
Auto completion for kubectl

### ISSUE THREAD

**Issue by solstarz** [kui-shell/AnimalApp#75]
Is it possible to add auto completion for kubectl?

**Comment by starpit** [comment]
hello! thanks for the feedback, much appreciated.

indeed, the base kui-core indeed has a tab completion extension API. this plugin utilizes that API to auto-complete namespaces and resource names: https://github.com/kui-shell/plugin-kubeui/blob/master/plugins/plugin-kubeui/src/lib/tab-completion.ts

PRs welcome to fill in the gaps!
